//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturaRepuestos = new HashSet<FacturaRepuesto>();
        }
    
        public long FacturaId { get; set; }
        public Nullable<long> TiendaId { get; set; }
        public Nullable<long> ClienteId { get; set; }
        public Nullable<long> MecanicoId { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Mecanico Mecanico { get; set; }
        public virtual Tienda Tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaRepuesto> FacturaRepuestos { get; set; }
    }
}
